DROP DATABASE IF EXISTS BaseDestinosJesus;

CREATE DATABASE BaseDestinosJesus DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE BaseDestinosJesus;

-- GRUPO 1
	CREATE TABLE 100_DIVISAS ( 
		100_idDivisa TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
		100_codDivisa CHAR(3) UNIQUE NOT NULL,
		100_nomDivisa VARCHAR(15) UNIQUE NOT NULL,
		100_divisaDolares FLOAT(12,6) NOT NULL,
		100_dolaresDivisa FLOAT(12,6) NOT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

	CREATE TABLE 200_CLIMAS ( 
		200_idClima TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
		200_nomClima VARCHAR(25) UNIQUE NOT NULL,
		200_tipoClima VARCHAR(15) NOT NULL,
		200_descClima TEXT NOT NULL,
		200_imgClima VARCHAR(100) UNIQUE NOT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

	CREATE TABLE 300_USUARIOS ( 
		300_idUsu MEDIUMINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
		300_nomUsu VARCHAR(50) NOT NULL,
		300_apeUsu VARCHAR(50) NOT NULL,
		300_email VARCHAR(100) UNIQUE NOT NULL,
		300_password VARCHAR(25) NOT NULL,
		300_descUsu TINYTEXT NOT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

	CREATE TABLE 400_CATEGORIAS ( 
		400_idCategoria TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
		400_nomCategoria VARCHAR(25) UNIQUE NOT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

	CREATE TABLE 500_REGIONESHORARIAS( 
		500_idHorario TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
		500_horaria CHAR(3) NOT NULL,
		500_latitud CHAR(10) NOT NULL,
		500_longitud CHAR(10) NOT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

	CREATE TABLE 600_CONTINENTES ( 
		600_idContinente TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
		600_nomContinente VARCHAR(20) UNIQUE NOT NULL,
		600_extensionKm2 BIGINT NOT NULL,
		600_habitantes BIGINT UNSIGNED NOT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- GRUPO 2
	CREATE TABLE 110_PAISES ( 
		110_idPais TINYINT UNSIGNED PRIMARY KEY,
		110_codPais CHAR(2) UNIQUE NOT NULL,
		110_nomPais VARCHAR(20) UNIQUE NOT NULL,
		110_extensionKm2 INT UNSIGNED NOT NULL,
		110_descCultura MEDIUMTEXT NOT NULL,
		110_bandera VARCHAR(100) UNIQUE NOT NULL,
		100_idDivisa TINYINT UNSIGNED NOT NULL,
		600_idContinente TINYINT UNSIGNED NOT NULL,
		CONSTRAINT fk_100_110 FOREIGN KEY ( 100_idDivisa ) REFERENCES 100_DIVISAS ( 100_idDivisa ),
		CONSTRAINT fk_600_110 FOREIGN KEY ( 600_idContinente ) REFERENCES 600_CONTINENTES ( 600_idContinente )
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

	CREATE TABLE 310_AMISTADES ( 
		300_idUsu MEDIUMINT UNSIGNED NOT NULL,
		300_idUsu2 MEDIUMINT UNSIGNED NOT NULL,
		CONSTRAINT pk_310 PRIMARY KEY( 300_idUsu, 300_idUsu2 ),
		310_fechaAmistad DATE NOT NULL,
		CONSTRAINT fk_300_310_0 FOREIGN KEY ( 300_idUsu ) REFERENCES 300_USUARIOS ( 300_idUsu ),
		CONSTRAINT fk_300_310_1 FOREIGN KEY ( 300_idUsu2 ) REFERENCES 300_USUARIOS ( 300_idUsu )
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

	CREATE TABLE 320_FOROS ( 
		320_idForo SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
		320_nomForo VARCHAR(200) UNIQUE NOT NULL,
		320_fechaCreacion DATE NOT NULL,
		300_idUsu MEDIUMINT UNSIGNED NOT NULL,
		CONSTRAINT fk_300_320 FOREIGN KEY ( 300_idUsu ) REFERENCES 300_USUARIOS ( 300_idUsu )
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
	
	CREATE TABLE 610_CONTINENTESCLIMAS ( 
		600_idContinente TINYINT UNSIGNED NOT NULL,
		200_idClima TINYINT UNSIGNED NOT NULL,
		CONSTRAINT fk_600_610 FOREIGN KEY ( 600_idContinente ) REFERENCES 600_CONTINENTES ( 600_idContinente ),
		CONSTRAINT fk_200_610 FOREIGN KEY ( 200_idClima ) REFERENCES 200_CLIMAS ( 200_idClima )
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- GRUPO 3
	CREATE TABLE 111_CIUDADES ( 
		111_idCiudad MEDIUMINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
		111_nomCiudad VARCHAR(100) NOT NULL,
		111_bCapital BOOLEAN NOT NULL,
		110_idPais TINYINT UNSIGNED NOT NULL,
		500_idHorario TINYINT UNSIGNED NOT NULL,
		200_idClima  TINYINT UNSIGNED NOT NULL,
		CONSTRAINT fk_110_111 FOREIGN KEY ( 110_idPais ) REFERENCES 110_PAISES ( 110_idPais ),
		CONSTRAINT fk_500_111 FOREIGN KEY ( 500_idHorario ) REFERENCES 500_REGIONESHORARIAS ( 500_idHorario ),
		CONSTRAINT fk_200_111 FOREIGN KEY ( 200_idClima ) REFERENCES 200_CLIMAS ( 200_idClima )
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

	CREATE TABLE 321_FOROSUSUARIOS ( 
		300_idUsu MEDIUMINT UNSIGNED,
		320_idForo SMALLINT UNSIGNED,
		321_fechaHoraInteraccion DATETIME,
		CONSTRAINT pk_321 PRIMARY KEY( 300_idUsu, 320_idForo, 321_fechaHoraInteraccion ),
		321_comentario TEXT NOT NULL,
		CONSTRAINT fk_500_321 FOREIGN KEY ( 300_idUsu ) REFERENCES 300_USUARIOS ( 300_idUsu ),
		CONSTRAINT fk_100_321 FOREIGN KEY ( 320_idForo ) REFERENCES 320_FOROS ( 320_idForo )
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- GRUPO 4
	CREATE TABLE 000_DESTINOS ( 
		000_idDestino MEDIUMINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
		000_nomdestino VARCHAR(100) NOT NULL,
		000_descDestino TINYTEXT NOT NULL,
		000_ubicacion VARCHAR(100) UNIQUE NOT NULL,
		111_idCiudad MEDIUMINT UNSIGNED NOT NULL,
		300_idUsu MEDIUMINT UNSIGNED NOT NULL, 
		400_idCategoria TINYINT UNSIGNED NOT NULL,
		CONSTRAINT fk_111_000 FOREIGN KEY ( 111_idCiudad ) REFERENCES 111_CIUDADES ( 111_idCiudad ),
		CONSTRAINT fk_300_000 FOREIGN KEY ( 300_idUsu ) REFERENCES 300_USUARIOS ( 300_idUsu ),
		CONSTRAINT fk_400_000 FOREIGN KEY ( 400_idCategoria ) REFERENCES 400_CATEGORIAS ( 400_idCategoria )
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- GRUPO 5
	CREATE TABLE 001_IMAGENES ( 
		001_idImg MEDIUMINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
		001_titulo VARCHAR(100) NOT NULL,
		001_fechaSubida DATE NOT NULL,
		001_rutaFichero VARCHAR(255) UNIQUE NOT NULL,
		000_idDestino MEDIUMINT UNSIGNED NOT NULL,
		300_idUsu MEDIUMINT UNSIGNED NOT NULL,
		CONSTRAINT fk_512_001 FOREIGN KEY ( 000_idDestino ) REFERENCES 000_DESTINOS ( 000_idDestino ),
		CONSTRAINT fk_300_001 FOREIGN KEY ( 300_idUsu ) REFERENCES 300_USUARIOS ( 300_idUsu )
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

	-- CREATE TABLE 002_DESTINOSCATEGORIAS ( 
	-- 	000_idDestino MEDIUMINT UNSIGNED,
	-- 	400_idCategoria TINYINT UNSIGNED,
	-- 	CONSTRAINT pk_002 PRIMARY KEY( 000_idDestino, 400_idCategoria ),
	-- 	CONSTRAINT fk_512_002 FOREIGN KEY ( 000_idDestino ) REFERENCES 000_DESTINOS ( 000_idDestino ),
	-- 	CONSTRAINT fk_400_002 FOREIGN KEY ( 400_idCategoria ) REFERENCES 400_CATEGORIAS ( 400_idCategoria )	
	-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;